name: codemagic_builder
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  dart_console: ^4.1.0
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mason_logger: ^0.2.14
  mockito: ^5.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
